permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name:Alex Yean
  email: ytf513@gmail.com
  link: http://ytf513.github.io
  weibo: http://weibo.com/ytf513
  github: http://github.com/ytf513

# 站点信息
title: 小尹的博客 
description: 小尹的博客
url: http://ytf513.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: site-picture.jpg
favicon: site-favicon.ico

# google analytics 设置
ga:
  id: UA-66553317-1
  url: ytf513.github.io

# disqus 设置
disqus:
  shortname: 
